Create knot company boards
CESARBR/knot-gateway-buildroot pull request #14
Opened 2019-07-23 01:53 UTC by pauloserrafh

Create a directory to place all knot related boards and minimizing the changes do buildroot mainline.
- configs/knot_raspberrypi3_defconfig should be a merge of `configs/raspberrypi3_defconfig` and `knot_gateway_defconfig`
- Updated build instructions to use new defconfig

2019-07-25 13:56 UTC, ramonhpr requested changes
Merge the commits: e6de41cc46608fb05e53ae9e8f5dc4362aba919c with ad04809b654441fb347e727abbaf853371a47d3d.

Copy the files will make us lost the git history. If you move the files git can recognize that the files were moved and we can keep the history from these files.

The only exception is genimage and the post-build files, the originals from raspberry3

2019-07-29 18:08 UTC, alla3 approved these changes

2019-07-29 18:17 UTC, ramonhpr approved these changes

2019-07-29 18:18 UTC, vitbaq approved these changes

2019-07-29 18:18 UTC, merged