Add KNoT-v03 defconfig
CESARBR/knot-gateway-buildroot pull request #52
Opened 2020-06-19 21:27 UTC by alla3

Add a new Defconfig to work with KNoT v03.00. This version does not use the KNoT Service, so it is not compatible with NRF's Things.

2020-07-01 15:36 UTC, vitbaq requested changes
Change the readme file to cover this new possibility of configuration;

2020-07-01 20:59 UTC, netoax submitted a review, later dismissed
Besides the @vitbaq review, this patch looks good to me.
Also, I submitted this [PR](https://github.com/CESARBR/knot-gateway-buildroot/pull/53) to remove knotd dependency from WebUI package. What do you think of rebasing on top of it?

2020-07-02 19:12 UTC, vitbaq approved these changes

2020-07-02 20:13 UTC, netoax approved these changes
LGTM!

2020-07-02 20:32 UTC, merged