Add a new service on Avahi
CESARBR/knot-gateway-buildroot pull request #8
Opened 2019-06-17 23:35 UTC by alla3

Add knot.service on Avahi to expose the gateway IP and Port through multicast DNS, allowing mobile clients such as Android Setup App to get this information and establish a connection with Web UI.

2019-06-18 10:24 UTC, jcorde requested changes
Remove IPV6 support **_so_** Android Setup App **_uses_** a stable IPV4 connection.

2019-06-18 10:30 UTC, jcorde requested changes
Please, mention the service that is being included on the title. 
_"a new service"_ is too generic. Something like _" Add local address multicasting to Avahi"_ might be more fit.

2019-06-18 12:16 UTC, ramonhpr requested changes

2019-06-18 12:16 UTC, ramonhpr commented on package/avahi/avahi.mk
> +define AVAHI_KNOT_SERVICE
Shouldn't we add this service to another package related to KNoT? This way we will always import this service independent if we build a KNoT image or not. 
I suggest we move this to the knot-web package as it's exposing its HTTP port. What do you think?
If you agree, remember to make avahi package a dependency from the knot-web package.

2019-06-18 12:16 UTC, ramonhpr commented on package/avahi/avahi.mk
> +define AVAHI_DISABLE_IPV6
You are going to disable IPv6 always doing that. 
Here you should create a flag to enable/disable IPv6 in ` package/avahi/Config.in` file. As the default is to enable ipv6 you should also add the flag disabling it on `configs/knot_gateway_defconfig`
Like this:
`ifeq ($(BR2_PACKAGE_AVAHI_DISABLE_IPV6),y)`
`... your changes`
`endif`

2019-06-20 22:01 UTC, alla3 commented on package/avahi/avahi.mk
> +define AVAHI_KNOT_SERVICE
Indeed. I have made changes to my previous version.

2019-06-21 21:16 UTC, ramonhpr approved these changes

2019-06-25 16:52 UTC, jcorde approved these changes
LGTM

2019-06-25 16:53 UTC, merged